// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/chatpb/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Ciphertext    string                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_chatpb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chatpb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_chatpb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ClientMessage) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *ClientMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Ciphertext    string                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsHistory     bool                   `protobuf:"varint,4,opt,name=is_history,json=isHistory,proto3" json:"is_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_chatpb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chatpb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_chatpb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ServerMessage) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *ServerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerMessage) GetIsHistory() bool {
	if x != nil {
		return x.IsHistory
	}
	return false
}

var File_internal_chatpb_chat_proto protoreflect.FileDescriptor

const file_internal_chatpb_chat_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/chatpb/chat.proto\x12\x06chatpb\"c\n" +
	"\rClientMessage\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\tR\n" +
	"ciphertext\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x80\x01\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\tR\n" +
	"ciphertext\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"is_history\x18\x04 \x01(\bR\tisHistory2G\n" +
	"\vChatService\x128\n" +
	"\x04Chat\x12\x15.chatpb.ClientMessage\x1a\x15.chatpb.ServerMessage(\x010\x01B&Z$server-client/internal/chatpb;chatpbb\x06proto3"

var (
	file_internal_chatpb_chat_proto_rawDescOnce sync.Once
	file_internal_chatpb_chat_proto_rawDescData []byte
)

func file_internal_chatpb_chat_proto_rawDescGZIP() []byte {
	file_internal_chatpb_chat_proto_rawDescOnce.Do(func() {
		file_internal_chatpb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_chatpb_chat_proto_rawDesc), len(file_internal_chatpb_chat_proto_rawDesc)))
	})
	return file_internal_chatpb_chat_proto_rawDescData
}

var file_internal_chatpb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_chatpb_chat_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: chatpb.ClientMessage
	(*ServerMessage)(nil), // 1: chatpb.ServerMessage
}
var file_internal_chatpb_chat_proto_depIdxs = []int32{
	0, // 0: chatpb.ChatService.Chat:input_type -> chatpb.ClientMessage
	1, // 1: chatpb.ChatService.Chat:output_type -> chatpb.ServerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_chatpb_chat_proto_init() }
func file_internal_chatpb_chat_proto_init() {
	if File_internal_chatpb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_chatpb_chat_proto_rawDesc), len(file_internal_chatpb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_chatpb_chat_proto_goTypes,
		DependencyIndexes: file_internal_chatpb_chat_proto_depIdxs,
		MessageInfos:      file_internal_chatpb_chat_proto_msgTypes,
	}.Build()
	File_internal_chatpb_chat_proto = out.File
	file_internal_chatpb_chat_proto_goTypes = nil
	file_internal_chatpb_chat_proto_depIdxs = nil
}
